# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김준형
title: Junior Backend Developer
email: rla5764v@gmail.com
website: https://gibro.tistory.com/

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username: JunHyeongKim73
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 준형-김-439474231
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: tistory
#   icon: fas fa-globe
#   url: https://gibro.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    **Node.js & Express 주니어 백엔드 개발자**입니다. Express & AWS EC2를 이용해 성균관대학교 학생들을 위한 <mark>웹 사이트 개발 프로젝트</mark>에 참여하여 팀장, API 개발, 배포 등을 맡았습니다. 대규모 서비스를 운영하는 백엔드 개발자가 되기 위해 현재는 Java & Spring을 공부 중이고, 개인 프로젝트를 진행할 예정입니다.

    **반복**을 싫어합니다. 반복 사용하는 코드는 함수화하고, 반복되는 작업은 코드화하려고 노력합니다. 반복되는 작업을 피하고자 Python으로 <mark>에브리타임 스크래핑 서비스</mark>를 개발한 경험이 있습니다.

content:
    - title: Projects # Title for the section
      layout: list # Type of content section (list/text)
      content:
          - layout: left
            title: 인턴십/산학협력
            caption: 2022.06 - 2022.08
            # sub_title: 소프트웨어학과
            # link: github.com/sproogen
            # link_text: Project Website
            # additional_links:
            #     - title: sproogen/modern-resume-theme
            #       icon: fab fa-github
            #       url: github.com/sproogen/modern-resume-theme
            #     # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            #     #   icon: fab fa-github
            #     #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
            quote: >
                알림 기능이 있는 정보제공 사이트 - 성균관대 학생들을 위한 IT 인턴십 및 산학협력 프로젝트 관련 정보제공
            description: | # this will include new lines to allow paragraphs
                - 팀장, 백엔드, 배포 담당
                - 프로젝트 로드맵 작성, 프로젝트 일정 관리
                - 학교 이메일을 이용한 로그인 API, 알림 API, 게시글 CRUD API, 관리자 API 및 관리자 페이지 개발
                - Node.js, Express, TypeORM, MySQL, AWS EC2, S3, React.js

          - layout: left
            title: File Sharing
            link: https://gibro.tistory.com/13
            # link_text: Project Website
            additional_links:
                - title: JunHyeongKim73/file-sharing-backend
                  icon: fab fa-github
                  url: https://github.com/JunHyeongKim73/file-sharing-backend
            caption: 2022.03 - 2022.04
            quote: >
                유저들끼리 파일을 공유하는 플랫폼 - 프론트엔드 개발 X
            description: | # this will include new lines to allow paragraphs
                - API 서버 구축 (개인 프로젝트)
                - 프로젝트 설계, DB 설계, API 설계 및 개발 (유저, 리뷰, 파일 관련 API), 인증 설계 및 API 개발
                - Postman을 이용한 API 테스트
                - Node.js, Express, MySQL, GCP VM, GCS

    - title: Skills # Title for the section
      layout: list # Type of content section (list/text)
      content:
          - layout: left
            title: Backend
            description: |
                - Node.js(Typescript), Java
                - Express, Spring Boot
                - TypeORM
                - MySQL
                - GCP VM, AWS EC2

          - layout: left
            title: Frontend
            description: |
                - React.js, HTML/CSS, Flutter
                - jQuery, Bootstrap

    #   - title: Experience # Title for the section
    #     layout: list # Type of content section (list/text)
    #     content:
    #       - layout: left
    #         title: The Boring Company
    #         link: boringcompany.com
    #         # link_text: boringcompany.com
    #         sub_title: Senior Network System Administrator
    #         caption: November 2017 - Present
    #         quote: >
    #           Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
    #         description: | # this will include new lines to allow paragraphs
    #             Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

    - title: Education # Title for the section
      layout: list # Type of content section (list/text)
      content:
          - layout: left
            title: 성균관대학교
            caption: 2018.02 - Present
            sub_title: 소프트웨어학과
            # quote: >
            #     Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
            description: | # this will include new lines to allow paragraphs
                - 멀티코어 컴퓨팅, 운영체제, 데이터베이스 개론 수업을 가장 흥미롭게 들음
                - 전공 학점: <mark>4.18/4.5</mark>

    # - title: Extra # Title for the section
    #   layout: list # Type of content section (list/text)
    #   content:
    #         - layout: left
    #           title: 키르기스스탄 IT 봉사
    #           caption: 2019.06 - 2019.07
    #           sub_title: 오쉬기술대학교
    #           # quote: >
    #           #     월드프렌즈 IT 봉사단
    #           description: | # this will include new lines to allow paragraphs
    #               - 월드프렌즈 IT 봉사단
    #               - Python 교육

    - title: Extra # Title for the section
      layout: text # Type of content section (list/text)
      content: |
          - 월드프렌즈 IT 봉사단 (오쉬기술대학교, 2019.06 - 2019.07)

# Footer
footer_show_references: true
# references_title: References on requests (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-seo-tag
